### ISSUE TITLE
Missing changes required within main.brs AND emphasis would be nice

### ISSUE THREAD

**Issue by grasponcrypto** [learnroku/crash-course#10]
1.  There are some necessary changes from lesson 2 to lesson 3 in main.brs which appears to be missing in the lesson.  Took a bit to figure out for a newbie:
````  
		msg = wait(0, m.port)
		msgType = type(msg)
		if msgType = "roSGScreenEvent"
			if msg.isScreenClosed() then return
		end if
````  

2.  Emphasis on a minor change which is easy to over look in lesson 3:
```` <ContentNode title = "DRAMA"/> ````
```` <category_node title = "HORROR" feed_url="..."/>````  
I think an emphasis should be placed on the fact that **ContentNode** is modified to **category_node** as this is a minor difference that is not immediately obvious and if users are manually modifying as i did, as opposed to copy and paste, then it can be quite an annoying learning lesson.

**Comment by grasponcrypto** [comment]
i placed a pull request for this.  feel free to fix phrasing if i used incorrect terminology

**Comment by learnroku** [comment]
I merged your PR, thanks for helping out!
