### ISSUE TITLE
In case you want some information on testing frameworks for roku development

### ISSUE THREAD

**Issue by georgejecook** [learnroku/crash-course#7]
I put a _lot_ of effort into making a top-tier mocha-inspired unit test framework for Roku, with examples, rich documentation and a couple of hours of video training.

I personally think it makes development way easier and more efficient (hence investing 150+ hours into it), so it might be that even new developers benefit from knowing about it.

https://github.com/georgejecook/rooibos

**Comment by timbeynart-nbcuni** [comment]
Cool. I no longer develop Roku apps but I'll spread the word. Thanks!
